package ir.hienob.noveo.ui

data class NoveoStrings(
    val menu: String = "Menu",
    val settings: String = "Settings",
    val allContacts: String = "All Contacts",
    val newChat: String = "New Chat",
    val stars: String = "Stars",
    val subscription: String = "Subscription",
    val profile: String = "Profile",
    val account: String = "Account",
    val preferences: String = "Preferences",
    val changelog: String = "Changelog",
    val themes: String = "Themes",
    val language: String = "Language",
    val privacy: String = "Privacy",
    val emojiStyle: String = "Emoji Style",
    val logout: String = "Logout",
    val saveChanges: String = "Save Changes",
    val displayName: String = "Display Name",
    val bio: String = "Bio",
    val userId: String = "User ID",
    val sessionId: String = "Session ID",
    val expiry: String = "Expiry",
    val changePassword: String = "Change Password",
    val deleteAccount: String = "Delete Account",
    val oldPassword: String = "Old Password",
    val newPassword: String = "New Password",
    val update: String = "Update",
    val cancel: String = "Cancel",
    val delete: String = "Delete",
    val deleteConfirmText: String = "Are you sure? This action is permanent and will remove all your data.",
    val selectLanguage: String = "Select Language",
    val messagePlaceholder: String = "Message",
    val noMessagesYet: String = "No messages yet",
    val selectChatHint: String = "Select a chat to start messaging",
    val searchPlaceholder: String = "Search...",
    val online: String = "online",
    val offline: String = "offline",
    val forwarded: String = "Forwarded",
    val sending: String = "Sending…",
    val clickToDownload: String = "Click to download",
    val whatNew: String = "What's New",
    val version: String = "Version",
    val premiumTitle: String = "Noveo Premium",
    val premiumBody: String = "Unlock exclusive themes, larger file uploads, and unique profile badges. Parity with web features is currently in progress.",
    val walletTitle: String = "Stars & Wallet",
    val walletBody: String = "Manage your digital balance for tips, gifts, and premium content. Parity with web wallet is still being implemented.",
    val privacyBody: String = "Security and visibility controls.",
    val emojiBody: String = "Choose your preferred emoji set.",
    val searchGlobal: String = "Global Search",
    val searchMessages: String = "Search messages",
    val loginTitle: String = "Welcome back",
    val signupTitle: String = "Join Noveo",
    val handlePlaceholder: String = "Username or Handle",
    val passwordPlaceholder: String = "Password",
    val loginButton: String = "Log In",
    val signupButton: String = "Sign Up",
    val switchSignup: String = "New here? Create an account",
    val switchLogin: String = "Already have an account? Log in",
    val onboardingTitle: String = "Secure. Fast. Modern.",
    val onboardingBody: String = "Experience the next generation of messaging with server-side encryption and web parity.",
    val onboardingAction: String = "Get Started",
    val onboardingPages: List<String> = listOf(
        "Chat with your contacts in one place.",
        "Jump into conversations quickly with the Noveo mobile shell.",
        "Stay synced and start messaging as soon as you sign in."
    )
)

private val translations = mapOf(
    "en" to NoveoStrings(),
    "fa" to NoveoStrings(
        menu = "منو",
        settings = "تنظیمات",
        allContacts = "مخاطبین",
        newChat = "گفتگوی جدید",
        stars = "ستاره‌ها",
        subscription = "اشتراک",
        profile = "پروفایل",
        account = "حساب کاربری",
        preferences = "اولویت‌ها",
        changelog = "تغییرات",
        themes = "تم‌ها",
        language = "زبان",
        privacy = "حریم خصوصی",
        emojiStyle = "سبک ایموجی",
        logout = "خروج",
        saveChanges = "ذخیره تغییرات",
        displayName = "نام نمایشی",
        bio = "بیوگرافی",
        userId = "شناسه کاربر",
        sessionId = "شناسه نشست",
        expiry = "انقضا",
        changePassword = "تغییر رمز عبور",
        deleteAccount = "حذف حساب",
        oldPassword = "رمز عبور قبلی",
        newPassword = "رمز عبور جدید",
        update = "بروزرسانی",
        cancel = "لغو",
        delete = "حذف",
        deleteConfirmText = "آیا مطمئن هستید؟ این عمل دائمی است و تمام داده‌های شما را حذف می‌کند.",
        selectLanguage = "انتخاب زبان",
        messagePlaceholder = "پیام",
        noMessagesYet = "هنوز پیامی وجود ندارد",
        selectChatHint = "یک گفتگو را برای شروع انتخاب کنید",
        searchPlaceholder = "جستجو...",
        online = "آنلاین",
        offline = "آفلاین",
        forwarded = "هدایت شده",
        sending = "در حال ارسال…",
        clickToDownload = "برای دانلود کلیک کنید",
        whatNew = "چه خبر؟",
        version = "نسخه",
        premiumTitle = "نوو پرمیوم",
        premiumBody = "باز کردن تم‌های اختصاصی، آپلود فایل‌های بزرگتر و نشان‌های پروفایل منحصر به فرد.",
        walletTitle = "ستاره‌ها و کیف پول",
        walletBody = "مدیریت موجودی دیجیتال برای انعام، هدایا و محتوای پرمیوم.",
        privacyBody = "کنترل‌های امنیتی و رویت‌پذیری.",
        emojiBody = "مجموعه ایموجی مورد علاقه خود را انتخاب کنید.",
        searchGlobal = "جستجوی جهانی",
        searchMessages = "جستجوی پیام‌ها",
        loginTitle = "خوش آمدید",
        signupTitle = "عضویت در نوو",
        handlePlaceholder = "نام کاربری",
        passwordPlaceholder = "رمز عبور",
        loginButton = "ورود",
        signupButton = "عضویت",
        switchSignup = "جدید هستید؟ حساب کاربری بسازید",
        switchLogin = "قبلاً ثبت نام کرده‌اید؟ وارد شوید",
        onboardingTitle = "امن. سریع. مدرن.",
        onboardingBody = "نسل بعدی پیام‌رسانی را با رمزگذاری سمت سرور تجربه کنید.",
        onboardingAction = "شروع کنید",
        onboardingPages = listOf(
            "با مخاطبین خود در یک جا گفتگو کنید.",
            "با پوسته موبایل نوو به سرعت وارد گفتگوها شوید.",
            "همگام بمانید و به محض ورود پیام‌رسانی را شروع کنید."
        )
    ),
    "ru" to NoveoStrings(
        menu = "Меню",
        settings = "Настройки",
        allContacts = "Контакты",
        newChat = "Новый чат",
        stars = "Звезды",
        subscription = "Подписка",
        profile = "Профиль",
        account = "Аккаунт",
        preferences = "Настройки",
        changelog = "Что нового",
        themes = "Темы",
        language = "Язык",
        privacy = "Конфиденциальность",
        emojiStyle = "Стиль эмодзи",
        logout = "Выйти",
        saveChanges = "Сохранить",
        displayName = "Отображаемое имя",
        bio = "О себе",
        userId = "ID пользователя",
        sessionId = "ID сессии",
        expiry = "Истекает",
        changePassword = "Изменить пароль",
        deleteAccount = "Удалить аккаунт",
        oldPassword = "Старый пароль",
        newPassword = "Новый пароль",
        update = "Обновить",
        cancel = "Отмена",
        delete = "Удалить",
        deleteConfirmText = "Вы уверены? Это действие необратимо и удалит все ваши данные.",
        selectLanguage = "Выбрать язык",
        messagePlaceholder = "Сообщение",
        noMessagesYet = "Нет сообщений",
        selectChatHint = "Выберите чат, чтобы начать общение",
        searchPlaceholder = "Поиск...",
        online = "в сети",
        offline = "не в сети",
        forwarded = "Переслано",
        sending = "Отправка…",
        clickToDownload = "Нажмите, чтобы скачать",
        whatNew = "Что нового",
        version = "Версия",
        premiumTitle = "Noveo Premium",
        premiumBody = "Разблокируйте эксклюзивные темы и уникальные значки профиля.",
        walletTitle = "Звезды и Кошелек",
        walletBody = "Управляйте своим цифровым балансом.",
        privacyBody = "Управление безопасностью и видимостью.",
        emojiBody = "Выберите предпочитаемый набор эмодзи.",
        searchGlobal = "Глобальный поиск",
        searchMessages = "Поиск сообщений",
        loginTitle = "С возвращением",
        signupTitle = "Регистрация в Noveo",
        handlePlaceholder = "Имя пользователя",
        passwordPlaceholder = "Пароль",
        loginButton = "Войти",
        signupButton = "Создать аккаунт",
        switchSignup = "Впервые здесь? Создайте аккаунт",
        switchLogin = "Уже есть аккаунт? Войти",
        onboardingTitle = "Безопасно. Быстро. Современно.",
        onboardingBody = "Испытайте новое поколение мессенджеров.",
        onboardingAction = "Начать",
        onboardingPages = listOf(
            "Общайтесь со всеми контактами в одном месте.",
            "Быстро переходите к разговорам с мобильной оболочкой Noveo.",
            "Оставайтесь синхронизированными и начинайте переписку сразу после входа."
        )
    ),
    "zh" to NoveoStrings(
        menu = "菜单",
        settings = "设置",
        allContacts = "联系人",
        newChat = "新建聊天",
        stars = "星星",
        subscription = "订阅",
        profile = "个人资料",
        account = "账号",
        preferences = "首选项",
        changelog = "更新日志",
        themes = "主题",
        language = "语言",
        privacy = "隐私",
        emojiStyle = "表情符号样式",
        logout = "退出登录",
        saveChanges = "保存更改",
        displayName = "显示名称",
        bio = "简介",
        userId = "用户 ID",
        sessionId = "会话 ID",
        expiry = "有效期至",
        changePassword = "修改密码",
        deleteAccount = "注销账号",
        oldPassword = "原密码",
        newPassword = "新密码",
        update = "更新",
        cancel = "取消",
        delete = "删除",
        deleteConfirmText = "您确定吗？此操作无法撤销，将删除您的所有数据。",
        selectLanguage = "选择语言",
        messagePlaceholder = "输入消息",
        noMessagesYet = "暂无消息",
        selectChatHint = "选择一个聊天开始沟通",
        searchPlaceholder = "搜索...",
        online = "在线",
        offline = "离线",
        forwarded = "转发",
        sending = "发送中…",
        clickToDownload = "点击下载",
        whatNew = "新功能",
        version = "版本",
        premiumTitle = "Noveo 会员",
        premiumBody = "解锁专属主题、更大大文件上传和独特个人资料徽章。",
        walletTitle = "星星与钱包",
        walletBody = "管理您的数字余额。",
        privacyBody = "安全与可见性控制。",
        emojiBody = "选择您喜欢的表情符号集。",
        searchGlobal = "全局搜索",
        searchMessages = "搜索消息",
        loginTitle = "欢迎回来",
        signupTitle = "加入 Noveo",
        handlePlaceholder = "用户名",
        passwordPlaceholder = "密码",
        loginButton = "登录",
        signupButton = "注册",
        switchSignup = "新用户？创建账号",
        switchLogin = "已有账号？登录",
        onboardingTitle = "安全。快速。现代。",
        onboardingBody = "体验下一代即时通讯应用。",
        onboardingAction = "立即开始",
        onboardingPages = listOf(
            "在一个地方与您的联系人聊天。",
            "使用 Noveo 移动外壳快速进入对话。",
            "保持同步，登录后即可开始发送消息。"
        )
    )
)

fun getStrings(languageCode: String): NoveoStrings {
    return translations[languageCode] ?: translations["en"]!!
}
