package ir.hienob.noveo.core.ui

/**
 * Platform-neutral strings used by the shared Noveo root and home surfaces.
 * Keep this file Android-free so Android and desktop can render the same UI skeleton.
 */
data class NoveoStrings(
    val languageCode: String = "en",
    val brandName: String = "Noveo",
    val next: String = "Next",
    val skip: String = "Skip",
    val onboardingAction: String = "Get Started",
    val onboardingPages: List<String> = listOf(
        "Chat with your contacts in one place.",
        "Jump into conversations quickly with the Noveo mobile shell.",
        "Stay synced and start messaging as soon as you sign in."
    ),
    val loginTitle: String = "Welcome back",
    val signupTitle: String = "Join Noveo",
    val switchSignup: String = "New here? Create an account",
    val switchLogin: String = "Already have an account? Log in",
    val loginButton: String = "Log In",
    val signupButton: String = "Sign Up",
    val handlePlaceholder: String = "Username or Handle",
    val passwordPlaceholder: String = "Password",
    val registerOnWebTitle: String = "Register on Noveo Web",
    val registerOnWebBody: String = "You have to register from Noveo Web for security reasons.",
    val openNoveoWeb: String = "Open Noveo Web",
    val menu: String = "Menu",
    val settings: String = "Settings",
    val allContacts: String = "All Contacts",
    val savedMessages: String = "Saved Messages",
    val newChat: String = "New Chat",
    val profile: String = "Profile",
    val account: String = "Account",
    val preferences: String = "Preferences",
    val themes: String = "Themes",
    val logout: String = "Logout",
    val searchPlaceholder: String = "Search...",
    val messagePlaceholder: String = "Message",
    val messages: String = "Messages",
    val noMessagesYet: String = "No messages yet",
    val selectChatHint: String = "Select a chat to start messaging",
    val online: String = "online",
    val offline: String = "offline",
    val typingPrivate: String = "typing...",
    val sending: String = "Sending…",
    val cannotSendMessage: String = "You cannot send messages in this chat.",
    val retry: String = "Retry",
    val refresh: String = "Refresh",
    val open: String = "Open",
    val close: String = "Close",
    val cancel: String = "Cancel",
    val reply: String = "Reply",
    val edit: String = "Edit",
    val delete: String = "Delete",
    val forward: String = "Forward",
    val download: String = "Download",
    val copyText: String = "Copy Text",
    val pinnedMessage: String = "Pinned Message",
    val forwarded: String = "Forwarded",
    val activeCall: String = "Active Call",
    val voiceChat: String = "Voice Chat"
)

fun coreNoveoStrings(languageCode: String?): NoveoStrings = when (languageCode?.lowercase()) {
    "fa" -> NoveoStrings(
        languageCode = "fa",
        next = "بعدی",
        skip = "رد کردن",
        onboardingAction = "شروع",
        onboardingPages = listOf(
            "با مخاطبانت در یک جا گفتگو کن.",
            "با پوسته موبایل Noveo سریع وارد گفتگوها شو.",
            "همگام بمان و بعد از ورود پیام دادن را شروع کن."
        ),
        loginTitle = "خوش برگشتی",
        signupTitle = "عضویت در Noveo",
        switchSignup = "تازه واردی؟ حساب بساز",
        switchLogin = "حساب داری؟ وارد شو",
        loginButton = "ورود",
        signupButton = "ثبت نام",
        handlePlaceholder = "نام کاربری یا هندل",
        passwordPlaceholder = "رمز عبور",
        registerOnWebTitle = "ثبت نام در وب Noveo",
        registerOnWebBody = "برای امنیت، ثبت نام باید از Noveo Web انجام شود.",
        openNoveoWeb = "باز کردن Noveo Web",
        menu = "منو",
        settings = "تنظیمات",
        allContacts = "مخاطبان",
        savedMessages = "پیام‌های ذخیره‌شده",
        newChat = "گفتگوی جدید",
        profile = "پروفایل",
        account = "حساب",
        preferences = "ترجیحات",
        themes = "پوسته‌ها",
        logout = "خروج",
        searchPlaceholder = "جستجو...",
        messagePlaceholder = "پیام",
        messages = "پیام‌ها",
        noMessagesYet = "هنوز پیامی نیست",
        selectChatHint = "یک گفتگو را برای شروع انتخاب کن",
        online = "آنلاین",
        offline = "آفلاین",
        typingPrivate = "در حال نوشتن...",
        sending = "در حال ارسال…",
        cannotSendMessage = "نمی‌توانی در این گفتگو پیام بفرستی.",
        retry = "تلاش دوباره",
        refresh = "تازه‌سازی",
        open = "باز کردن",
        close = "بستن",
        cancel = "لغو",
        reply = "پاسخ",
        edit = "ویرایش",
        delete = "حذف",
        forward = "بازفرستادن",
        download = "دانلود",
        copyText = "کپی متن",
        pinnedMessage = "پیام سنجاق‌شده",
        forwarded = "بازفرستاده‌شده",
        activeCall = "تماس فعال",
        voiceChat = "گفتگوی صوتی"
    )
    else -> NoveoStrings(languageCode = languageCode ?: "en")
}
